import { computed, ref } from 'vue'
import { defineStore } from 'pinia'
import { db } from '@/firebase'
import { arrayRemove, collection, deleteDoc, doc, serverTimestamp, setDoc, updateDoc } from "firebase/firestore"
import { useFirestore } from '@vueuse/firebase/useFirestore'

/*
   User
      id - generated by auth
      email - read/only - from auth
      firstName
      lastName
      username
      images
         ...itemImage
      settings
         itemHeaders[]
         galleryThumbOptions[]
         itemThumbOptions[]
         searches[]
         showHiddenItems
         notifyViaEmail
         notifyViaMessage
         soloMode - boolean, initially false
      messagingTokens[]
         device
         token
      dateCreated
      dateModified
*/
const USER_TABLE = 'users'

export const useUserStore = defineStore('user', () => {
   const userCollection = collection(db, USER_TABLE)
   function userDoc(id)  { return doc(db, USER_TABLE, id) }
   
   const users = useFirestore(userCollection)   
   const userIdToUser = computed(() => { return users.value ? new Map(users.value.map((obj) => [obj.id, obj])) : new Map() })
   
   const userId = ref('')
   const userQuery = computed(() => userId.value && userDoc(userId.value))
   const user = useFirestore(userQuery, null)
   const userExists = computed(() => user.value ? true : false)
   
   function getUser(id) { return userIdToUser.value.get(id) }
   function getUsername(id) { return userIdToUser.value.has(id) ? userIdToUser.value.get(id).username : "" }

   function setUser(user) {
      console.log("setUser", user) 
      userId.value = user.id
      const userToSet = { ...user, dateCreated: serverTimestamp(), dateModified: serverTimestamp() }
      setDoc(userDoc(userToSet.id), userToSet)
   }

   function updateUser(updatedUser) {
      console.log("updateUser", updatedUser) 
      const userToUpdate = { ...updatedUser, dateModified: serverTimestamp() }
      updateDoc(userDoc(userToUpdate.id), userToUpdate)
   }

   const myFullName = computed(() => user.value ? (user.value.firstName ? user.value.firstName + " ": "") + user.value.lastName : "")
   const mySettings = computed(() => user.value && user.value.settings ? user.value.settings : {} )
   const soloMode   = computed(() => mySettings.value?.soloMode)

   function updateSettings(settings) {
      updateDoc(userDoc(userId.value), { 
         settings: settings,
         dateModified: serverTimestamp(),
      })
   }

   function deleteUser(id) {
      // console.log("deleteUser", id) 
      // backend cleans up items/groups/galleries/wall and deletes user from auth
      deleteDoc(doc(userCollection, id))
   }

   function updateImages(images) {
      updateDoc(userDoc(userId.value), { images: images, dateModified: serverTimestamp() })
   }

   function removeImage(image) {
      updateDoc(userDoc(userId.value), { images:arrayRemove(image), dateModified:serverTimestamp() })
   }

   return { 
      userId, user, users, userIdToUser, userExists, getUser, getUsername, setUser, updateUser, deleteUser,
      myFullName, mySettings, soloMode, updateSettings, updateImages, removeImage
   }
})
